name: Terraform GKE Deployment (Dev Only)

on:
  pull_request:
    paths:
      - 'envs/dev/**'
      - 'modules/**'
  push:
    branches:
      - main
    paths:
      - 'envs/dev/**'
      - 'modules/**'
  workflow_dispatch: {} # enables manual runs

env:
  GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}
  TF_IN_AUTOMATION: true

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Terraform Init
        run: terraform -chdir=envs/dev init

      - name: Terraform Plan
        run: terraform -chdir=envs/dev plan -var-file=terraform.tfvars -out=tfplan

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: dev-apply   # <-- creates the approval gate

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Terraform Init
        run: terraform -chdir=envs/dev init

      - name: Terraform Apply
        run: terraform -chdir=envs/dev apply -auto-approve tfplan

  destroy-plan:
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}


      - name: Terraform Init
        run: terraform -chdir=envs/dev init

      - name: Terraform Destroy Plan
        run: terraform -chdir=envs/dev plan -destroy -var-file=terraform.tfvars -out=tfplan-destroy

  destroy-apply:
    runs-on: ubuntu-latest
    needs: destroy-plan
    environment: dev-apply-destroy   # <-- second approval gate

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Terraform Init
        run: terraform -chdir=envs/dev init

      - name: Terraform Destroy Apply
        run: terraform -chdir=envs/dev destroy -auto-approve
